# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('register_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('surname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('quantity', models.IntegerField(default=1)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('arrive_city', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Carrier')),
            ],
        ),
    ]
